import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";

import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import About from "@/components/About/About";
import Contact from "@/components/Contact/Contact";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <title>DriveXpo</title>
        </head>
        <body className={inter.className}>
          <SignedIn>
            <NavBar />
            {children}
            <About />
            <Contact />
            <Footer />
          </SignedIn>
          <SignedOut>
            <SignIn />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
